pydgin:
  restart: always
  build: ./pydgin
  ports:
    - "8001:8000"
  links:
    - postgres:postgres
    - elasticsearch:elasticsearch
  entrypoint: sh /usr/src/app/entrypoint.sh
  volumes:
    - /usr/src/app/pydgin
    - ./pydgin/settings_secret.py:/usr/src/app/pydgin/pydgin/settings_secret.py
    - ./pydgin/entrypoint.sh:/usr/src/app/entrypoint.sh
  env_file: .env

elasticsearch:
  restart: always
  image: elasticsearch:2.2.0
  ports:
    - "9201:9200"
  volumes:
    - ./elasticsearch/config:/usr/share/elasticsearch/config 
    - ./elasticsearch/esdata:/usr/share/elasticsearch/data
  cap_add:
    - IPC_LOCK
  ulimits:
    memlock: -1
  environment:
    - ES_HEAP_SIZE=2g
  user: elasticsearch

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - pydgin
  links:
    - pydgin:pydgin

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  environment:
    POSTGRES_USER: webuser
    POSTGRES_PASSWORD: webuser
    POSTGRES_DB: pydgin_authdb

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: echo "postgres data volume"
  
#rserve:
#  restart: always
#  build: ./rserve/
#  entrypoint: /usr/src/entrypoint.sh
#  volumes:
#    - /usr/src/
#    - ./rserve/entrypoint.sh:/usr/src/entrypoint.sh
#    - ./rserve/rserve.conf:/usr/src/rserve.conf
#    - ./rserve/rserve.R:/usr/src/rserve.R
#    - ./rserve/vcf2ld.R:/tmp/vcf2ld.R
#  ports:
#    - "6311:6311"
