pydgin:
  restart: always
  build: ./pydgin
  ports:
    - "8000:8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app
  env_file: .env
  command: /usr/local/bin/gunicorn pydgin.wsgi:application -w 2 -b :8000

elasticsearch:
  restart: always
  image: elasticsearch:2.2.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - ./elasticsearch/config:/usr/share/elasticsearch/config 
    - ./elasticsearch/esdata:/usr/share/elasticsearch/data
  environment:
    - ES_HEAP_SIZE=2g

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

